name: "CI"

env:
  OPTIMISM_MAINNET_RPC_URL: ${{ secrets.OPTIMISM_MAINNET_RPC_URL }}
  FOUNDRY_PROFILE: "ci"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "Install pnpm dependencies"
        run: "pnpm install"

      - name: "Install foundry libs"
        run: "forge install"

      - name: "Build the contracts"
        run: "pnpm build"

      - name: "Add build summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["build"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "Install pnpm dependencies"
        run: "pnpm install"

      - name: "Install foundry libs"
        run: "forge install"

      - name: "Build the contracts"
        run: "pnpm build"

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Run the fork tests for Optimism"
        run: "pnpm test:op"

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
